name: Build SyncMe app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: nuget restore src/SyncMe/SyncMe.sln

    # - name: Bump apps version
    #   shell: pwsh
    #   run: |
    #       cd src/SyncMe
    #       .\bump_version.ps1

    - name: Build SyncMe.Android
      run: |
          msbuild src/SyncMe/SyncMe.Android/SyncMe.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
    
    - name: Build SyncMe.iOS
      run: |
        msbuild src/SyncMe/SyncMe.IOS/SyncMe.IOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug  
